# Generated by Django 4.1.7 on 2023-03-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fliq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
