# Generated by Django 4.1.7 on 2023-03-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fliq', '0002_remove_contactinfo_phone_number_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
